# Generated by Django 4.2 on 2024-05-23 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_inmueble_propietario'),
        ('app', '0004_solicitudarriendo_estado'),
    ]

    operations = [
    ]
